# Generated by Django 6.0.3 on 2026-04-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_mealcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
