# Generated by Django 6.0.3 on 2026-04-22 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
